image: python:3.6-onbuild

stages:
  - lint
  - build
  - test

lint-python:
  stage: lint
  script:
  - pip install flake8
  - flake8 --config=flake8.conf --exclude=venv/ --exclude=.git/ .

check-migrations:
  stage: build
  script:
    # setup python requirements
    - pip install virtualenv
    - virtualenv venv
    - . venv/bin/activate
    - pip install -r requirements.txt --isolated
    # check migrations
    - python3 manage.py makemigrations --check
    - python3 manage.py migrate
