# Generated by Django 3.1 on 2020-08-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White')], max_length=255)),
                ('brand', models.CharField(choices=[('vw', 'VW'), ('fiat', 'Fiat'), ('gm', 'GM'), ('ford', 'Ford'), ('honda', 'Honda')], max_length=255)),
                ('body', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], max_length=255)),
                ('year', models.IntegerField()),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='garage.garage')),
            ],
        ),
    ]
