# Generated by Django 3.1 on 2020-08-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='garage',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
